### ISSUE TITLE
I have 1 problem ? when import laravel project 

### ISSUE THREAD

**Issue by phamducthinhdev** [haruncpi/laravel-id-generator#1]
<img width="1023" alt="Screen Shot 2019-11-05 at 11 00 58 AM" src="https://user-images.githubusercontent.com/27260441/68177671-b3adf480-ffbb-11e9-81c2-a7400455b9d5.png">

**Comment by haruncpi** [comment]
Your field data type is not varchar but you're trying to generate string type id like INV-000001. You must have to change the field data type to varchar if you wanna generate this kind of id or choose another format of ID generation.

**Comment by phamducthinhdev** [comment]
<img width="643" alt="Screen Shot 2019-11-05 at 1 29 58 PM" src="https://user-images.githubusercontent.com/27260441/68184053-9b94a000-ffd0-11e9-9299-a1551e272c17.png">
<img width="549" alt="Screen Shot 2019-11-05 at 1 31 22 PM" src="https://user-images.githubusercontent.com/27260441/68184055-9b94a000-ffd0-11e9-86f5-c3a0716fb4e1.png"> I have change id in VARCHAR

**Comment by haruncpi** [comment]
problem fix or not?
You just generate the $id but not used it in your code.
According to your id format. Your field must be varchar which already you have. Table must have empty records before using this package. Check with a simple get route by returning $id it's generating id or not.
```
Route::get('/test',function(){
 $id = IdGenerator::generate(['table' => 'sites', 'length' => 10, 'prefix' =>'INV-']);
 return $id;
})
```
or you can simply test with php artisan tinker
