### ISSUE TITLE
Using library with Postresql

### ISSUE THREAD

**Issue by youssef-ghrib** [haruncpi/laravel-id-generator#11]
I have tried using your library with Postgresql but it throws this error:

ERROR:  syntax error at or near "describe"
LINE 1: describe deliveries
        ^
SQL state: 42601
Character: 1

It seams to me that $colsType = DB::select('describe ' . $table); is the issue because describe is not supported by Postgresql.
Could you provide a workaround for this?

**Comment by haruncpi** [comment]
Try now
