### ISSUE TITLE
table field type is int but prefix is string

### ISSUE THREAD

**Issue by JemCdo** [haruncpi/laravel-id-generator#19]
Hi @haruncpi! I hope you're doing well.
your package is awesome.

I just have an issue with inserting a value with a type string in the prefix key.

I tried the same example in the docs as bellow:
$id = IdGenerator::generate(['table' => 'invoices', 'length' => 10, 'prefix' =>'INV-']);

And I'm getting this error: "table field type is int but prefix is string"

Thanks

**Comment by haruncpi** [comment]
Error message is clearly showing you what is wrong.

Your table ID field data type is integer but you are trying to generate string type of ID.

To fix that, change your table field data type as varchar with length 10 or bigger.

**Comment by loicgeek** [comment]
@haruncpi  but I am not generating for the id, it is for another fiels that is a string

**Comment by haruncpi** [comment]
> @haruncpi but I am not generating for the id, it is for another fiels that is a string

Pass the `field` parameter like 
`'field' => 'your_field_name'`

**Comment by QuophiAwuah** [comment]
The field column should be an integer so in order to attach  a string to it, just append the "INV-" to the generated id, this is what i mean
$id = IdGenerator::generate(['table' => 'invoices', 'length' => 10, 'prefix' =>date(y)]);

$new_id = "INV-".$id;

this should do it
