### ISSUE TITLE
Undefined property: stdClass::$maxId {"exception":"[object] (ErrorException(code: 0): Undefined property: stdClass::$maxId 

### ISSUE THREAD

**Issue by dendoy** [haruncpi/laravel-id-generator#20]
error with pgsql at vendor/haruncpi/laravel-id-generator/src/IdGenerator.php:107)

**Comment by hakimfauzi23** [comment]
Hey I have same issue, it's solved yet?

**Comment by dendoy** [comment]
change $queryResult[0]->maxId to $queryResult[0]->maxid (lowercase)

**Comment by hakimfauzi23** [comment]
It's worked, thanks!!
