### ISSUE TITLE
Auto generated id not increamenting

### ISSUE THREAD

**Issue by SabirPatel-hp** [haruncpi/laravel-id-generator#21]
i use the package in my admin panel, Id generated very nice but it don't increamenting.
it's as 2104020001, 2104020001
I want as 2104020001, 0002, 0003
so please help me as soon as possible.

**Comment by haruncpi** [comment]
What you have tried (code)?

**Comment by SabirPatel-hp** [comment]
Now it's working
Actually I forgot to give field name to generateID() now problem is solved

Thank you
From
Sabir Patel
