### ISSUE TITLE
TypeError Unsupported operand types: string + int

### ISSUE THREAD

**Issue by aa-hridoy** [haruncpi/laravel-id-generator#22]
TypeError
Unsupported operand types: string + int

**Comment by haruncpi** [comment]
Not clear about the issue.
- What is your php, laravel version?
- what is exactly error message?

**Comment by aa-hridoy** [comment]
php 7.3
laravel 8

**Comment by Cigoler** [comment]
You've probably not specified the right table and/or field you are assigning it to

**Comment by haruncpi** [comment]
Try v1.0.9 [Fixed Unsupported operand types: string + int]
