### ISSUE TITLE
Exactly where do you paste the code

### ISSUE THREAD

**Issue by TemplarWorld** [haruncpi/laravel-id-generator#24]
You're missing documentation on exactly what files to generate or where to paste the code in a laravel application. Migrations? if so where?
Great idea, just missing details for deployment

**Comment by haruncpi** [comment]
You can generate by the controller. Example:

```php
$config = [
    'table' => 'todos',
    'length' => 6,
    'prefix' => date('y')
];

$id = IdGenerator::generate($config);

$todo = new Todo();
$todo->id = $id;
$todo->title = $request->get('title');
$todo->save();
```

or In your model add a `boot `method. The ID will automatically generate when a new record will be added.
```php
public static function boot()
{
    parent::boot();
    self::creating(function ($model) {
        $model->uuid = IdGenerator::generate(['table' => $this->table, 'length' => 6, 'prefix' =>date('y')]);
    });
}
```
