### ISSUE TITLE
Possible to offset the generation of numbers, like instead of 00001 start from 001234

### ISSUE THREAD

**Issue by Cigoler** [haruncpi/laravel-id-generator#26]
Basically as the title says, as it stands the number begins from 1 upwards, I'm wondering if it's possible to offset it to start from say 100, or 1000 etc. Any help appreciated.

**Comment by haruncpi** [comment]
It not supported by the package. Although, you can insert an ID `P001234` first then generate the ID with the same length. Then it will generate from next like `P001235`.
