### ISSUE TITLE
user_id field type is bigint but prefix is string

### ISSUE THREAD

**Issue by Orsai1998** [haruncpi/laravel-id-generator#27]
$id = IdGenerator::generate(['table' => 'patient_details','field'=>'user_id', 'length' => 5, 'prefix' => $request->ind_code.'-']);

**Comment by Orsai1998** [comment]
and when i tried to use varchar field got error A non-numeric value encountered

**Comment by haruncpi** [comment]
Try to update the package. If the problem still exists. Please let me know your Laravel version and PHP.
