### ISSUE TITLE
id field type is bigint but prefix is string

### ISSUE THREAD

**Issue by rofequl** [haruncpi/laravel-id-generator#29]
```
$code_generate = 'LYB';
$insert = DB::table('orders')->insertGetId([
            'user_id' => Auth::user()->id,
            'order_code' => IdGenerator::generate(['table' => 'orders', 'length' => 9, 'prefix' => $code_generate]),
            'payment_type' => (int)$request->payment_type,
            'address_id' => (int)$address->id,
            'no_of_product' => count($order_list),
            'subtotal' => $subtotal,
            'shipping' => $shipping,
            'total' => $total,
        ]);
```
![image](https://user-images.githubusercontent.com/26442131/122647670-3232b800-d147-11eb-9a9c-212eacc0383d.png)

**Comment by ilhamrafi44** [comment]
Add the field `field` to the config,

> ```
> $code_generate = 'LYB';
> $insert = DB::table('orders')->insertGetId([
>             'user_id' => Auth::user()->id,
>             'order_code' => IdGenerator::generate(['table' => 'orders', 'length' => 9,'field' => 'order_code', 'prefix' => $code_generate]),
> ```
> 
> ![image](https://user-images.githubusercontent.com/26442131/122647670-3232b800-d147-11eb-9a9c-212eacc0383d.png)
