### ISSUE TITLE
IdGenerator doest generate unique IDs

### ISSUE THREAD

**Issue by m33ts4k0z** [haruncpi/laravel-id-generator#31]
Hello,

Using this package in my project like this in an orders model:

```
 public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model->order_number = IdGenerator::generate(['table' => 'orders', 'length' => 6, 'prefix' => date('y')]);
        });
    }
```

But it doesnt generate unique ids:

https://i.imgur.com/FvRKnlj.png

Any idea why?

**Comment by kingofcold** [comment]
I have the same issue, and it doesn't work on the id column

**Comment by haruncpi** [comment]
By default, it works with the table `id` field. If you want to use a custom field then you have to pass the parameter `field`. [Check doc](https://laravelarticle.com/laravel-custom-id-generator#parameters)

```php
IdGenerator::generate(['table' => 'orders', 'field' => 'order_number', 'length' => 6, 'prefix' => date('y')]);
```
The output will be like
```
210001
210002
210003
....
```

**Comment by m33ts4k0z** [comment]
Hello,

I did try that but the IDs are still not unique: 

https://i.imgur.com/c7x7o2y.png

https://i.imgur.com/xzC7qoR.png

**Comment by haruncpi** [comment]
@m33ts4k0z  For your setup:
- keep id field as normal auto increment (pk)
- order_number (unique)
- clear all table data before try.

```php
IdGenerator::generate(['table' => 'orders', 'field' => 'order_number', 'length' => 6, 'prefix' => date('y')]);
```
