### ISSUE TITLE
Undefined array key 0

### ISSUE THREAD

**Issue by kingofcold** [haruncpi/laravel-id-generator#33]
I am having an error of:

ErrorException
Undefined array key 0

and the code is:
public static function boot()
    {
        parent::boot();
        self::creating(function (Product $model) {  
            $model->barcodeID = IdGenerator::generate(['table'=>'products','length'=> 4,'prefix'=>date('y')]);
        });
    }

any ideas?

**Comment by kingofcold** [comment]
I got to work if i use name as the field, but the output id is the same, it doesn't increment the ids to make it unique.
any help?

**Comment by haruncpi** [comment]
You are using a custom field instead of `id` field. So you have to pass the [parameter](https://laravelarticle.com/laravel-custom-id-generator#parameters) for it also.  You missed `'field' => 'barcodeID'`
```php
public static function boot()
{
    parent::boot();
    self::creating(function ($model) {
        $model->barcodeID = IdGenerator::generate(['table'=>'products','field'=>'barcodeID', 'length'=> 4,'prefix'=> date('y')]);
    });
}
```
Output will be like
```
2101
2102
2103
....
```
