### ISSUE TITLE
 Undefined array key 0 

### ISSUE THREAD

**Issue by tiru55** [haruncpi/laravel-id-generator#34]
$task = Task::create([
            'task_id'  => IdGenerator::generate(['table' => 'tasks', 'length' => 6, 'prefix' => 'TSK-']),
)

I have tried using Idgenerator, but i am getting this error Undefined array key 0

**Comment by haruncpi** [comment]
You are using the custom field `task_id` and you did not pass `field` parameter value. [Check doc](https://laravelarticle.com/laravel-custom-id-generator#parameters)
```php
$task = Task::create([
  'task_id' => IdGenerator::generate(['table' => 'tasks', 'field'=>'task_id', 'length' => 6, 'prefix' => 'TSK-']),
)
```
Keep in mind, you are using `TSK-` string prefix. So your `task_id` data type must have to be `varchar`
