### ISSUE TITLE
Suddenly stopped generating unique numbers

### ISSUE THREAD

**Issue by RST281** [haruncpi/laravel-id-generator#36]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'А-22-0001'

Suddenly stopped generating unique numbers

My helper code:

![Безымяннsdfgsый](https://user-images.githubusercontent.com/6259462/147947913-9da11676-faae-4a40-9ec8-4f6c4e6aef7d.png)

**Comment by Maru-Yasa** [comment]
still stop generating unique id, any solution?
