### ISSUE TITLE
Problem with different prefix and same table:

### ISSUE THREAD

**Issue by lucabecchetti** [haruncpi/laravel-id-generator#37]
I i want to generate an id with this data:

array:5 [▼
  "table" => "estimates"
  "length" => 8
  "field" => "number"
  "prefix" => "E-"
  "reset_on_prefix_change" => false
]

If my table contains: 

E-000001
IND-000001

next code is: "E-000001"

Why?

**Comment by haruncpi** [comment]
Different prefix is not the problem. It's problem with different prefix length.
Use the same length of prefix.
