### ISSUE TITLE
Count also other prefixes in the table!

### ISSUE THREAD

**Issue by sergeByishimo** [haruncpi/laravel-id-generator#4]
Love the package!

The package does count in the records that uses other prefixes in the same table, so that when you want to start with a new prefix it should start with 001.

Make it required to count only the records with the given prefix.

Happy to submit a PR.

**Comment by haruncpi** [comment]
On prefix change reset id support added. Please check the documentation. https://laravelarticle.com/laravel-custom-id-generator

**Comment by sergeByishimo** [comment]
thank you brother!
