### ISSUE TITLE
ErrorException  : A non-numeric value encountered

### ISSUE THREAD

**Issue by henryejemuta** [haruncpi/laravel-id-generator#5]
ErrorException  : A non-numeric value encountered

  at C:\xampp\htdocs\myshop\vendor\haruncpi\laravel-id-generator\src\IdGenerator.php:50
    46|         if ($total[0]->total) {
    47|             $maxQuery = sprintf("SELECT MAX(SUBSTR(%s,%s,%s)) maxId FROM %s %s",
    48|                         $field, ($prefixLength + 1), $idLength, $configArr['table'], $whereString);
    49|             $maxId = DB::select($maxQuery);
  > 50|             $maxId = $maxId[0]->maxId + 1;
    51|
    52|             return $configArr['prefix'] . str_pad($maxId, $idLength, '0', STR_PAD_LEFT);
    53|         } else {
    54|             return $configArr['prefix'] . str_pad(1, $idLength, '0', STR_PAD_LEFT);

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("A non-numeric value encountered", "C:\xampp\htdocs\myshop\vendor\haruncpi\laravel-id-generator\src\IdGenerator.php")
      C:\xampp\htdocs\myshop\vendor\haruncpi\laravel-id-generator\src\IdGenerator.php:50

  2   Haruncpi\LaravelIdGenerator\IdGenerator::generate(["users", "INV"])
      C:\xampp\htdocs\myshop\app\User.php:56

  

User boot function:
`
    public static function boot()
    {
        parent::boot();
        static::creating(function ($user) {
            $user->pin = IdGenerator::generate(['table' => 'users', 'length' => 10, 'prefix' =>'INV']);
        });
    }`

**Comment by haruncpi** [comment]
You are using `INV` prefix it's a string, so your user table id field data type must be varchar
