### ISSUE TITLE
A non-numeric value encountered 

### ISSUE THREAD

**Issue by Anoob007** [haruncpi/laravel-id-generator#6]
A:\THRILOK\demo\demo\
ErrorException
A non-numeric value encountered
http://127.0.0.1:8000/1

        44
        A:\THRILOK\demo\demo\vendor\haruncpi\laravel-id-generator\src\IdGenerator.php
        Illuminate\Foundation\Bootstrap\HandleExceptions
        :50
        43
        A:\THRILOK\demo\demo\vendor\haruncpi\laravel-id-generator\src\IdGenerator.php
        Haruncpi\LaravelIdGenerator\IdGenerator
        :50
        42
        App\Http\Controllers\a
        :11

    1 unknown frame
        40
        A:\THRILOK\demo\demo\vendor\laravel\framework\src\Illuminate\Routing\Controller.php
        Illuminate\Routing\Controller
        :54
        39
        Illuminate\Routing\ControllerDispatcher
        :45
        38
        Illuminate\Routing\Route
        :219
        37
        Illuminate\Routing\Route
        :176
        36
        Illuminate\Routing\Router
        :681
        35
        Illuminate\Pipeline\Pipeline
        :130
        34
        Illuminate\Routing\Middleware\SubstituteBindings
        :41
        33
        Illuminate\Pipeline\Pipeline
        :171
        32
        Illuminate\Foundation\Http\Middleware\VerifyCsrfToken
        :76
        31
        Illuminate\Pipeline\Pipeline
        :171
        30
        Illuminate\View\Middleware\ShareErrorsFromSession
        :49
        29
        Illuminate\Pipeline\Pipeline
        :171
        28
        Illuminate\Session\Middleware\StartSession
        :56
        27
        Illuminate\Pipeline\Pipeline
        :171
        26
        Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse
        :37
        25
        Illuminate\Pipeline\Pipeline
        :171
        24
        Illuminate\Cookie\Middleware\EncryptCookies
        :66
        23
        Illuminate\Pipeline\Pipeline
        :171
        22
        Illuminate\Pipeline\Pipeline
        :105
        21
        Illuminate\Routing\Router
        :683
        20
        Illuminate\Routing\Router
        :658
        19
        Illuminate\Routing\Router
        :624
        18
        Illuminate\Routing\Router
        :613
        17
        Illuminate\Foundation\Http\Kernel
        :170
        16
        Illuminate\Pipeline\Pipeline
        :130
        15
        Illuminate\Foundation\Http\Middleware\TransformsRequest
        :21
        14
        Illuminate\Pipeline\Pipeline
        :171
        13
        Illuminate\Foundation\Http\Middleware\TransformsRequest
        :21
        12
        Illuminate\Pipeline\Pipeline
        :171
        11
        Illuminate\Foundation\Http\Middleware\ValidatePostSize
        :27
        10
        Illuminate\Pipeline\Pipeline
        :171
        9
        Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode
        :63
        8
        Illuminate\Pipeline\Pipeline
        :171
        7
        Fideloper\Proxy\TrustProxies
        :57
        6
        Illuminate\Pipeline\Pipeline
        :171
        5
        Illuminate\Pipeline\Pipeline
        :105
        4
        Illuminate\Foundation\Http\Kernel
        :145
        3
        Illuminate\Foundation\Http\Kernel
        :110
        2
        :55
        1
        :21

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError :50
A:\THRILOK\demo\demo\vendor\haruncpi\laravel-id-generator\src\IdGenerator.php:50

        }

 

        $field = array_key_exists('field', $configArr) ? $configArr['field'] : 'id';

        $prefixLength = strlen($configArr['prefix']);

        $idLength = $configArr['length'] - $prefixLength;

        $whereString = '';

 

        if (array_key_exists('where', $configArr)) {

            $whereString .= " WHERE ";

            foreach ($configArr['where'] as $row) {

                $whereString .= $row[0] . "=" . $row[1] . " AND ";

            }

        }

        $whereString = rtrim($whereString, 'AND ');

 

 

        $totalQuery = sprintf("SELECT count(%s) total FROM %s %s", $field, $configArr['table'], $whereString);

        $total = DB::select($totalQuery);

 

        if ($total[0]->total) {

            $maxQuery = sprintf("SELECT MAX(SUBSTR(%s,%s,%s)) maxId FROM %s %s",

                        $field, ($prefixLength + 1), $idLength, $configArr['table'], $whereString);

            $maxId = DB::select($maxQuery);

            $maxId = $maxId[1]->maxId + 1;

 

            return $configArr['prefix'] . str_pad($maxId, $idLength, '0', STR_PAD_LEFT);

        } else {

            return $configArr['prefix'] . str_pad(1, $idLength, '0', STR_PAD_LEFT);

        }

    }

}

**Comment by haruncpi** [comment]
Please post your ID config and your table id field datatype.

**Comment by Anoob007** [comment]
Fex it
