### ISSUE TITLE
Request - Foereing key as parameter

### ISSUE THREAD

**Issue by Flamigni** [haruncpi/laravel-id-generator#9]
Hello,
It should be great if you could add a foreign key in the parameter to start a new invoice number.
For example i have invoices related to offices. My need is to seperate invoices numbers per offices, so if i could put the office id in parameters it would be useful.
Thanks for your great work.

**Comment by haruncpi** [comment]
You can use office id as a prefix and set reset on prefix change parameter true. It will generate id like below

1010001
1010002
1010003
1020001
1020002
...

[101,102 is office id]
